# SETO-Versal 交易系统配置文件

# 系统配置
system:
  name: "SETO-Versal Trading System"
  version: "0.9.0"
  log_dir: "logs"
  data_dir: "data"

# 市场配置
market:
  datasource: "tushare"
  universe: "hs300"
  trading_hours:
    open: "09:30"
    close: "15:00"
    lunch_start: "11:30"
    lunch_end: "13:00"

# 模式配置
mode_configs:
  backtest:
    update_interval: 300
    use_cache: true
    risk_level: "high"
    max_drawdown: 0.05
    max_position_size: 0.3
    trailing_stop: true
    # 回测专用配置
    backtest:
      start_date: "2022-01-01"  # 回测开始日期
      end_date: "2022-12-31"    # 回测结束日期
      capital: 1000000          # 初始资金
      commission: 0.0003        # 佣金费率
      slippage: 0.0001          # 滑点
      benchmark: "000300.SH"    # 基准指数，用于计算相对收益
      data_source: "local"      # 数据来源: local或api
      frequency: "day"          # 回测频率: day, hour, minute
      price_type: "close"       # 使用哪种价格: open, high, low, close
      adjust_type: "qfq"        # 复权类型: 前复权(qfq)，后复权(hfq)，不复权(none)
  paper:
    update_interval: 60
    use_cache: true
    risk_level: "medium"
    max_drawdown: 0.03
    max_position_size: 0.25
    trailing_stop: true
  live:
    update_interval: 30
    use_cache: false
    risk_level: "low"
    max_drawdown: 0.02
    max_position_size: 0.2
    trailing_stop: true

# 代理配置
agents:
  - type: "trend"
    name: "trend_agent_1"
    confidence_threshold: 0.7
    max_positions: 5
    weight: 1.0
    lookback_period: 20
    trend_threshold: 0.05
    # 技术指标参数
    parameters:
      ema_short: 12
      ema_long: 26
      macd_signal: 9
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      bollinger_period: 20
      bollinger_std: 2.0
    # 哪些模式启用此代理
    mode_restrictions:
      backtest: true
      paper: true
      live: true

  - type: "reversal"
    name: "reversal_agent_1"
    confidence_threshold: 0.75
    max_positions: 3
    weight: 0.8
    lookback_period: 14
    # 技术指标参数
    parameters:
      rsi_period: 14
      rsi_oversold: 25
      rsi_overbought: 75
      stoch_k_period: 14
      stoch_d_period: 3
      stoch_slow: 3
      stoch_oversold: 20
      stoch_overbought: 80
    # 哪些模式启用此代理
    mode_restrictions:
      backtest: true
      paper: true
      live: false

  - type: "fast_profit"
    name: "fast_profit_agent"
    confidence_threshold: 0.8
    max_positions: 7
    weight: 0.6
    lookback_period: 5
    # 技术指标参数
    parameters:
      profit_target: 0.05
      stop_loss: 0.03
      atr_period: 14
      atr_multiplier: 2
      volume_threshold: 1.5
    # 哪些模式启用此代理
    mode_restrictions:
      backtest: true
      paper: false
      live: false

  - type: "defensive"
    name: "defensive_agent"
    confidence_threshold: 0.65
    max_positions: 5
    weight: 0.7
    lookback_period: 30
    # 技术指标参数 
    parameters:
      beta_threshold: 0.8
      dividend_yield: 0.03
      pe_max: 20
      volatility_max: 0.25
      correlation_threshold: 0.5
    # 哪些模式启用此代理
    mode_restrictions:
      backtest: true
      paper: true
      live: true

# 风险控制配置
risk:
  max_drawdown: 0.05
  max_position_size: 0.3
  max_leverage: 1.0
  stop_loss: 0.02
  take_profit: 0.05
  trailing_stop: true
  trailing_stop_distance: 0.01
  # 新增风险控制参数
  risk_management:
    position_sizing: "percent_risk"  # percent_risk, equal_risk, percent_equity
    risk_per_trade: 0.01             # 每笔交易风险比例 (1%)
    max_correlation: 0.7             # 持仓最大相关性
    sector_exposure_limit: 0.3       # 每个行业最大敞口
    max_open_trades: 10              # 最大同时持仓数量
    volatility_filter: true          # 是否使用波动率过滤
    vix_threshold: 30                # VIX指数阈值

# 进化配置
evolution:
  population_size: 100
  generations: 50
  mutation_rate: 0.1
  crossover_rate: 0.8
  elite_size: 10
  tournament_size: 3
  # 新增进化参数
  evolution_settings:
    fitness_function: "sharpe"       # 适应度函数: sharpe, sortino, calmar, omega
    optimize_interval: "weekly"      # 优化频率: daily, weekly, monthly
    parallel_processing: true        # 是否使用并行处理
    parameter_ranges:                # 参数搜索范围
      ema_short: [5, 20]
      ema_long: [20, 50]
      rsi_period: [7, 21]
      atr_period: [10, 20]
      trend_threshold: [0.02, 0.1]

# 数据源配置
data_sources:
  tushare:
    token: "your_tushare_token"
    api_url: "http://api.tushare.pro"
    timeout: 10
    retry_count: 3
    cache_days: 7
  local:
    data_path: "data/market/historical"
    file_format: "csv"
    default_fields: ["open", "high", "low", "close", "volume", "amount"]

# 数据预处理配置
data_preprocessing:
  fill_missing: "ffill"        # 填充缺失值方法: ffill, bfill, zero, mean
  outlier_detection: "zscore"  # 异常值检测: zscore, iqr, none
  normalization: "minmax"      # 归一化方法: minmax, zscore, none
  feature_engineering:         # 特征工程配置
    technical_indicators: true
    fundamental_data: false
    sentiment_analysis: false
    alternative_data: false

# 报告和可视化配置
reporting:
  save_report: true
  report_path: "reports"
  plot_equity_curve: true
  plot_drawdown: true
  plot_trades: true
  plot_position_size: true
  metrics:
    - "total_return"
    - "annualized_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    - "sortino_ratio"
